version: '2.2'
services:
  dynamodb:
    command: "-jar DynamoDBLocal.jar -inMemory"
    image: "amazon/dynamodb-local:latest"
    working_dir: /home/dynamodblocal
    ports:
      - "8000:8000"
  localstack:
    image: "localstack/localstack:latest"
    environment:
      - "SERVICES=cloudwatch"
      - "USE_SSL=true"
    healthcheck:
      test: "awslocal cloudwatch list-metrics"
      interval: 5s
      timeout: 10s
      start_period: 10s
    ports:
      - "4566:4566"
    depends_on:
      - dynamodb
  kinesis-mock:
    image: "ghcr.io/etspaceman/kinesis-mock:${DOCKER_TAG_VERSION}"
    environment:
      - "LOG_LEVEL=TRACE"
    healthcheck:
      test: "curl --fail http://localhost:4569/healthcheck || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "4567:4567"
      - "4568:4568"
      - "4569:4569"
  ready:
    image: "library/hello-world"
    depends_on:
      localstack:
        condition: service_healthy
      kinesis-mock:
        condition: service_healthy
networks:
  default:
    external:
      name: ${DOCKER_NET_NAME}