name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cbor_enabled: [true, false]
        service_port: [4567, 4568]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Validate build
      run: sbt validate
      env:
        JAVA_OPTS: -Duser.country=US -Duser.language=en
        CBOR_ENABLED: ${{ matrix.cbor_enabled }}
        SERVICE_PORT: ${{ matrix.service_port }}