name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: [2.13.4]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Validate build
      run: sbt ++${{ matrix.scala }} validate
      env:
        JAVA_OPTS: -Duser.country=US -Duser.language=en